name: greenhydrogen
channels:
  - conda-forge
dependencies:
  - python=3.12
  - numpy=1.26.4
  - pandas
  - scikit-learn
  - xgboost
  - lightgbm
  - catboost
  - joblib
  - matplotlib
  - seaborn
  - streamlit
  - geopandas
  - pyarrow
  - fpdf
  - openpyxl
  - shap=0.45.0
  - ipython
  - pypdf2>=3.0
  - plotly>=5.19
  - python-kaleido>=1.0.0   # Conda package that bundles headless Chromium
